apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-server
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      initContainers:
        - args:
            - wait
            - --for=condition=complete
            - --timeout=300s
            - job/db-create
          image: d3fk/kubectl:v1.18
          name: db-create-wait
      containers:
        - envFrom:
          - secretRef:
              name: jambonz
          env:
            - name: HTTP_PORT
              value: "3000"
            - name: JAMBONE_API_VERSION
              value: v1
          image: jambonz/jambonz-api-server:latest
          name: api-server
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always