apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: influxdb
  name: influxdb
spec:
  serviceName: influxdb
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      name: influxdb
      labels:
        app: influxdb
    spec:
      containers:
        - image: influxdb:1.8
          name: influxdb
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: api
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          ports:
            - containerPort: 8086
              name: api
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: influxdb-claim
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: influxdb-claim
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: influxdbstorageclass
