apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sbc-inbound
  name: sbc-inbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbc-inbound
  template:
    metadata:
      labels:
        app: sbc-inbound
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      initContainers:
        - args:
            - wait
            - --for=condition=complete
            - --timeout=300s
            - job/db-create
          image: d3fk/kubectl:v1.18
          name: db-create-wait
      containers:
        - envFrom:
          - secretRef:
              name: jambonz
          image: jambonz/sbc-inbound:latest
          name: sbc-inbound
          resources: {}
      restartPolicy: Always
