apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registrar
  name: registrar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registrar
  template:
    metadata:
      labels:
        app: registrar
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - envFrom:
          - secretRef:
              name: jambonz
          image: jambonz/sbc-registrar:latest
          name: registrar
          resources: {}
      restartPolicy: Always
