apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: drachtio-sbc-sip
  labels:
    app: drachtio-sbc-sip
spec:
  selector:
    matchLabels:
      app: drachtio-sbc-sip
  template:
    metadata:
      labels:
        app: drachtio-sbc-sip
    spec:
      nodeSelector:
        voip-environment: edge
      hostNetwork: true
      tolerations:
        - key: "voip-edge"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: drachtio
          image: drachtio/drachtio-server:0.8.12
          args: ['drachtio', '--cloud-deployment', '--contact', 'sip:*:5060;transport=tcp']
          envFrom:
            - secretRef:
                name: jambonz
          ports:
            - containerPort: 9022
              protocol: TCP
            - containerPort: 5060
              protocol: UDP
            - containerPort: 5060
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/drachtio.conf.xml
              name: drachtio-sbc-sip-conf
              subPath: drachtio.conf.xml
        - name: sbc-call-router
          image: jambonz/sbc-call-router:latest
          envFrom:
            - secretRef:
                name: jambonz
          env:
            - name: HTTP_PORT
              value: "4000"
        - name: sbc-options-handler
          image: jambonz/sbc-options-handler:latest
          envFrom:
            - secretRef:
                name: jambonz
        - name: sbc-registrar
          image: jambonz/sbc-registrar:latest
          envFrom:
            - secretRef:
                name: jambonz
        - name: sbc-inbound
          image: jambonz/sbc-inbound:latest
          envFrom:
            - secretRef:
                name: jambonz
        - name: sbc-outbound
          image: jambonz/sbc-outbound:latest
          envFrom:
            - secretRef:
                name: jambonz
      restartPolicy: Always
      volumes:
      - name: drachtio-sbc-sip-conf
        configMap:
          name: drachtio-sbc-sip-conf
          items:
          - key: drachtio.conf.xml
            path: drachtio.conf.xml