apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: drachtio-sbc-rtp
  labels:
    app: drachtio-sbc-rtp
spec:
  selector:
    matchLabels:
      app: drachtio-sbc-rtp
  template:
    metadata:
      labels:
        app: drachtio-sbc-rtp
    spec:
      nodeSelector:
        voip-environment: edge
      hostNetwork: true
      tolerations:
        - key: "voip-edge"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: drachtio
          image: drachtio/drachtio-server:0.8.12
          args: ['drachtio', '--contact', 'sip:*:5064;transport=udp,tcp', '--port', '9023']
        - name: rtpengine-sidecar
          image: jambonz/rtpengine-sidecar:latest
          envFrom:
            - secretRef:
                name: jambonz
        - name: rtpengine 
          image: jambonz/rtpengine:latest 
          args: ['rtpengine']
          envFrom:
            - secretRef:
                name: jambonz
      restartPolicy: Always
