apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: call-router
  name: call-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: call-router
  template:
    metadata:
      labels:
        app: call-router
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - envFrom:
          - secretRef:
              name: jambonz
          env:
            - name: HTTP_PORT
              value: "4000"
          image: jambonz/sbc-call-router:latest
          name: call-router
          resources: {}
      restartPolicy: Always
