apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jambonzwebapp
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: webapp.k8sdev.jambonz.us
      http:
        paths:
        - backend:
            service: 
              name: webapp 
              port: 
                number: 3001
          path: /
          pathType: Prefix
